# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprogress',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
