# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20160425_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
