# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprogress',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
